name: busecke_abernathey_2019
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy
  - cartopy
  - dask
  - distributed
  - matplotlib
  - python=3.8
  - numpy
  - scipy
  - xarray
  - netcdf4
  - nc-time-axis
